server.port=8080

spring.security.user.name=admin
spring.security.user.password=admin123

#SPRING JDBC Configuration
spring.datasource.url=jdbc:oracle:thin:@10.54.6.20:1765:AXISCUST
spring.datasource.username=GBM
spring.datasource.password=gbm
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#SPRING JDBC Configuration ENDS here

#SPRING DATA JPA Configuration 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#SPRING DATA JPA Configuration ensa here